### ISSUE TITLE
User should not be able to rent without selecting the city and vehicle 

### ISSUE THREAD

**Issue by HIMANIRANI** [itsmesauravk/VROOM_Car_Rental#28]
In our project, the rent request can be submitted without specifying the city and vehicle. This inconsistency needs to be addressed, ensuring that the selected city and vehicle are clearly displayed when making a request.

**Comment by Nischal1111** [comment]
Fixed the issue where the user can rent a vehicle with default setting where the city and vehicle is set to none.
