### ISSUE TITLE
Reservation Limit Enforcement for Users with Pending Reservations

### ISSUE THREAD

**Issue by HIMANIRANI** [itsmesauravk/VROOM_Car_Rental#29]
If a user already has two pending reservations, they should not be allowed to make any further reservations until at least one of the pending ones has been resolved.

**Comment by Nischal1111** [comment]
FIxed the issue and user can now only make 2 reservations if there are already two requests in the pending status.

**Comment by HIMANIRANI** [comment]
Well Done!
