### ISSUE TITLE
Prevent Duplicate Bookings on Same Date

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#30]
When a user attempts to make a booking for a date on which they already have an existing booking, the system should display an error message informing the user that they cannot book for the same date again. This prevents duplicate bookings and ensures efficient utilization of resources

**Comment by Nischal1111** [comment]
Fixed the issue and now user cannot make two reservations with same city, same vehicle, and same start date.
