### ISSUE TITLE
 Failure to Display Alert Message on Signup Page

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#59]
The signup page on our platform is currently experiencing a critical functionality issue wherein alert messages are not displayed upon user actions triggering such notifications. This absence of alerts significantly impacts user experience and poses potential risks such as confusion, data submission errors, and decreased user engagement.

**Comment by rohanmgr130** [comment]
There was missing of alert message.
<img width="391" alt="Screenshot 2024-05-16 at 14 26 12" src="https://github.com/itsmesauravk/VROOM_Car_Rental/assets/137970206/8a2588a5-0a24-44e3-8c63-2f80983cc91e">
