### ISSUE TITLE
Do not allow Users to Enter Text in Phone Number Field 

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#68]
Users can input text in the phone number field within the Vroom project's user interface. This should not be allowed and the code must restrict users from entering special characters or text along with the phone number, potentially leading to confusion or errors during data entry.
![image (2)](https://github.com/itsmesauravk/VROOM_Car_Rental/assets/129931965/87e20428-0041-4224-b657-2e646278ad32)

**Comment by Nischal1111** [comment]
I have fixed the bug and now only numbers can be registered in the phone details.
