### ISSUE TITLE
Backend Data Update Not Reflected in UI Buttons 

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#69]
After initiating an action that sends details to the backend, such as confirming a rental booking, the UI buttons (e.g., cancel, confirm) remain unchanged. Despite successfully updating the backend data, this discrepancy in the UI buttons' states may confuse users, leading to uncertainty about the status of their actions.

**Comment by Nischal1111** [comment]
Yes, I have fixed the bug, where the UI button did not change its status even after clicking confirm. Now, the code successfully runs and the button is altered as per the condition.
