### ISSUE TITLE
Sign-Up Form Allows Phone Number Input negative digits

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#70]
During sign-up, users can enter negative numbers in the phone number field, preventing them from inputting complete phone numbers. This limitation obstructs users from providing accurate contact information, which is crucial for communication and account verification purposes.

**Comment by BisekhKarki** [comment]
Thank you Manisha for reaching me out about the isssue. I have fixed the bug where now user cannot register with negative numbers.
