### ISSUE TITLE
Backend Failure to Process User-Requested Booking Confirmations 

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#71]
Users are encountering a critical issue where their requests for booking confirmations are not being successfully processed by the backend system. Despite users initiating the confirmation process through the frontend interface, the backend fails to acknowledge or update the booking status accordingly, leading to potential service disruptions and customer dissatisfaction.

**Comment by itsmesauravk** [comment]
I have found the bug that was creating the problem while doing confirmation of  car in user profile. I have fix that bug and updated the code
