### ISSUE TITLE
Users Can Send More Than One Booking Request on Vroom Platform When They Should Only Send One

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#73]
Right now, Vroom doesn't work like it's supposed to. It's meant for users only to send one booking request. But, users can send more than one. They'll get a message saying they can't book again, but if they refresh the page, they can book again. This messes up what the project was supposed to do.

**Comment by Nischal1111** [comment]
Fixed the issue and now users can only book once before their request is approved.
<img width="1440" alt="Screenshot 2024-05-15 at 6 11 44 AM" src="https://github.com/itsmesauravk/VROOM_Car_Rental/assets/102789731/b257baef-954e-454c-9bdf-fc2ff9b59721">
