### ISSUE TITLE
Admin Unable to Delete Distributers in Admin Panel

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#74]
Currently, the system's admin panel does not allow administrators to delete distributors. This means that once distributors are added to the system, there is no option for the admin to remove them. This limitation prevents the admin from managing the list of distributors effectively and maintaining the system's integrity.

**Comment by rohanmgr130** [comment]
Bug solve there was some error while fetching.
<img width="405" alt="image" src="https://github.com/itsmesauravk/VROOM_Car_Rental/assets/137970206/dfa04281-fa11-40dd-a5f6-56fbcdeaa94a">
