### ISSUE TITLE
Rental Client Status Not Reset and Car Displayed as "Not Found" After Reset in Distributor Panel

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#75]
Within the distributor panel, there's an issue where resetting the rental client status doesn't work as expected. Even after attempting to reset the status, it remains unchanged. Additionally, when checking the status of a car, it shows up as "Not Found" even though the car is present in the system. This inconsistency in data retrieval and status resetting disrupts the distributor's ability to effectively manage rental clients and their associated cars.

**Comment by itsmesauravk** [comment]
I have found the part that was creating the problem by not sending car details to the response. I have fixed the code, updated it and push to github.
