### ISSUE TITLE
Lack of Clarity in Rental Car Cost and Booking Duration Details in UI

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#78]
The current user interface (UI) design for the rental car booking system shows a notable lack of clarity regarding the presentation of rental car costs and booking duration details. This issue arises primarily from unclear and easily accessible information regarding pricing breakdowns and booking duration options.

**Comment by Nischal1111** [comment]
I have fixed the data details and now the total cost is updated.
