### ISSUE TITLE
 User should not have access to Settings Page  After Logout

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#79]
Currently, users can access the settings page even after logging out of their account. However, the settings page should only be accessible to logged-in users. This presents a security vulnerability and a potential breach of user privacy, as unauthorized individuals could gain access to sensitive account information and make unauthorized changes.

**Comment by Nischal1111** [comment]
I have fixed the issue where users can access the settings page even after logging out.
