### ISSUE TITLE
Addressing Missing Delete Button and Redundant Reset Button

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#81]
Our system has two big problems that are making it hard for our distributors to do their job well. Firstly, there's no button to delete cars when they're  not needed anymore. This means our listings get cluttered and confusing. Secondly, 'Reset' button works to reset the booking of the car and that button still appears when the car is available.

**Comment by Nischal1111** [comment]
Fixed the issue and now distributors can easily remove the unwanted cars and reset button rendering is updated.
