### ISSUE TITLE
User Unable to Cancel Booking Request

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#84]
Some users are having trouble canceling their booking requests in the app. Even though they follow the steps shown, like going to the booking details and pressing "Cancel," they still get errors or can't finish canceling.

**Comment by rohanmgr130** [comment]
Bug fixed there was problem while fetching there was messing of id 
<img width="471" alt="image" src="https://github.com/itsmesauravk/VROOM_Car_Rental/assets/137970206/29359f46-c6e7-494b-91dc-6cf94e394c32">
