### ISSUE TITLE
Error to cancel Payment Details  on Booking Form

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#86]
When attempting to cancel the payment details on the booking form, an error message is displayed in the console which is causing the product to run smoothly and user are not able to cancel the booking.

**Comment by itsmesauravk** [comment]
fix: resolve error in code
Resolved the issue that was causing the error and updated the code.
![Screenshot from 2024-05-17 23-31-37](https://github.com/itsmesauravk/VROOM_Car_Rental/assets/127291490/79276392-9e62-4a2e-aa3f-6a1b8c8b3f61)
