### ISSUE TITLE
Rental Clients' Cars Not Displayed While Accepting User Requests

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#87]
When attempting to accept a user request, the rental clients' car details are not displayed. This issue occurs because the car details are not being received from the backend.

**Comment by itsmesauravk** [comment]
I have find the issue and fixed the code with the comment. I have commit the changes to github.
![Screenshot from 2024-05-17 23-22-43](https://github.com/itsmesauravk/VROOM_Car_Rental/assets/127291490/bc454cdb-c76f-4f63-8cfe-baf1be055916)
