### ISSUE TITLE
Error While Updating User Profile

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#88]
An error occurs when attempting to update the user profile. This issue prevents users from successfully saving changes to their profile information.
![image](https://github.com/itsmesauravk/VROOM_Car_Rental/assets/129931965/fff13e6e-9636-436e-8fab-856ed6d5b235)

**Comment by itsmesauravk** [comment]
I have triggered the issue and update the code , now user can easily update their profile and data will be stored in the database. I have commit the changes to github.
