### ISSUE TITLE
Side Navbar Display Issue

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#89]
The side navbar in the project is not displaying correctly. It either overlaps with the main content, appears out of alignment, or is not responsive on different screen sizes. This issue affects the user experience as the navigation is critical for accessing different sections of the application.

**Comment by BisekhKarki** [comment]
The bug of  UI in admin dashboard which was overlapping over has been fixed. Thank you for reaching me out.
