### ISSUE TITLE
Inconsistent Button Sizes in Admin Panel

### ISSUE THREAD

**Issue by Manisha-Tmg** [itsmesauravk/VROOM_Car_Rental#94]
We have observed that the buttons in the admin panel are not consistent in size. This inconsistency affects the overall user experience and may cause confusion or difficulty in navigation for users. Some buttons appear larger or smaller than others (Especially logout) which does not align with our design guidelines.

**Comment by BisekhKarki** [comment]
The bug has been fixed. Thanks for reaching me out about the issue
